services:
  cell-conquest-services:
    image: oven/bun
    ports:
      - "0.0.0.0:3000:3000"
    working_dir: /app
    volumes:
      - ./apps/cell-conquest-services/dist:/app:ro
    env_file:
      - ./apps/cell-conquest-services/.env
    environment:
      - REDIS_URL=redis://cell-conquest-redis:6379
    depends_on:
      - cell-conquest-redis
    command: ['bun', 'run', '/app/index.js']
    networks:
      - app_network

  cell-conquest-crons:
    image: oven/bun
    working_dir: /app
    volumes:
      - ./apps/cell-conquest-crons/dist:/app:ro
    env_file:
      - ./apps/cell-conquest-crons/.env
    environment:
      - REDIS_URL=redis://cell-conquest-redis:6379
    depends_on:
      - cell-conquest-redis
    command: ['bun', 'run', '/app/index.js']
    networks:
      - app_network

  cell-conquest-redis:
    image: redis:alpine
    command: ['redis-server', '--port', '6379']
    volumes:
      - cell-conquest-redis-data:/data
    networks:
      - app_network

  # cloudflare-ddns:
  #   image: oznu/cloudflare-ddns:latest
  #   env_file:
  #     - .env.cloudflare
  #   restart: unless-stopped
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  cell-conquest-redis-data:
